### ISSUE TITLE
Dataset From SAL Hospital

### ISSUE THREAD

**Issue by AmbiTyga** [debadyuti23/GraphCovidNet#1]
I would like to experiment the GraphCovidNet specifically on the dataset from SAL hospital, share the link to the dataset, please.

**Comment by thepritam** [comment]
Hello , @AmbiTyga  ,
Thank you for showing interest in our work.  
All the datasets used for the experiment are given in the readme file with their links.

**Comment by AmbiTyga** [comment]
Can you tell me which one is that? please specify its link over here!

**Comment by debadyuti23** [comment]
Hi @AmbiTyga,
Although we have not used the aforementioned dataset in our work, you can go through the following:
 1. https://link.springer.com/article/10.1007/s11356-020-10133-3---> paper which used SAL hospital dataset
 2. http://salhospital.com/ --> link for SAL dataset
 Hope this solves your issue

**Comment by AmbiTyga** [comment]
I have gone through them and they don't contain any relevant information to access the dataset from SAL hospital.
